export default function sitemap() {
  const baseUrl = new URL(process.env.NEXT_PUBLIC_BASE_URL || "https://plusxelectric.com");
  return [
    {
      url             : baseUrl,
      lastModified    : new Date("2026-06-17T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 1,
    },
    {
      url             : `${baseUrl}mobile-ev-charging-dubai`,
      lastModified    : new Date("2026-07-17T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-pickup-dropoff-charging-service`,
      lastModified    : new Date("2026-08-04T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}public-ev-charging-stations`,
      lastModified    : new Date("2026-08-04T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ev-accessories`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-breakdown-assistance`,
      lastModified    : new Date("2026-08-04T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}commercial-ev-charging-solutions`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charge-share`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-car-insurance`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}sustainability`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}complete-ev-care-dubai`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-dubai-apartments`,
      lastModified    : new Date("2026-06-10T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },



    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/portable-ev-charger-ac-7kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/portable-ev-charger-ac-11kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/wall-charger-ac-7kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/wall-charger-ac-11kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/wall-charger-ac-22kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/movable-charger-dc-20kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/movable-charger-dc-30kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/wallbox-charger-dc-20kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/wallbox-charger-dc-30kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/high-power-dc-60kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ac-dc-ev-chargers/high-power-dc-120kw`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },


    {
      url             : `${baseUrl}ev-charger-installation-uae/ev-accessories/wall-mount-bracket-for-portable-ev-charger`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    {
      url             : `${baseUrl}ev-charger-installation-uae/ev-accessories/carry-bag-for-portable-ev-charger`,
      lastModified    : new Date("2026-07-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.9,
    },
    
    
    // {
    //   url             : `${baseUrl}mobility-solution`,
    //   lastModified    : new Date(),
    //   changeFrequency : "weekly",
    //   priority        : 0.9,
    // },
    // {
    //   url             : `${baseUrl}ev-roadside-assistance-service-dubai`,
    //   lastModified    : new Date(),
    //   changeFrequency : "weekly",
    //   priority        : 0.9,
    // },
    // {
    //   url             : `${baseUrl}ev-roadside-assistance-service`,
    //   lastModified    : new Date(),
    //   changeFrequency : "weekly",
    //   priority        : 0.9,
    // },
    
    {
      url             : `${baseUrl}blog`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}exploring-the-benefits-of-electric-vehicles-in-the-uae-a-comprehensive-guide`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}the-rise-of-electric-vehicles-in-the-uae-a-comprehensive-overview`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}electric-vehicle-leasing-and-renting-options-in-the-uae`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}the-future-of-electric-mobility-innovations-and-trends-in-the-uae`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}what-to-do-when-your-ev-battery-dies-in-dubai`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}why-every-dubai-ev-driver-should-know-about-plusx-electrics-roadside-rescue`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}the-rise-of-evs-in-dubai-and-the-growing-need-for-smart-charging-solutions`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}ev-range-anxiety-is-real-here-how-plusx-emergency-ev-charging-pod-solves-it`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}five-scenarios-where-ev-roadside-assistance-becomes-a-lifesaver`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}top-ten-locations-in-dubai-where-ev-drivers-most-need-emergency-charging`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}how-plusx-electric-is-revolutionizing-emergency-ev-charging-in-dubai`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}stuck-with-a-drained-ev-battery-heres-how-on-demand-charging-saves-the-day`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}why-ev-roadside-assistance-is-a-must-have-for-every-ev-owner`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}why-a-personal-ev-charger-is-a-smart-choice-in-the-uae`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}road-trip-in-the-uae-with-an-ev-here-why-you-need-backup-support`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}common-charging-challenges-ev-owners-face-in-dubai`,
      lastModified    : new Date("2026-03-25T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}top-five-electric-vehicles-dominating-the-roads-in-dubai`,
      lastModified    : new Date("2026-04-01T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}how-plusx-electric-ev-charging-keeps-delivery-companies-running-in-dubai`,
      lastModified    : new Date("2026-04-08T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}the-benefits-for-ev-owner-having-plusx-electric-app`,
      lastModified    : new Date("2026-04-15T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}why-every-ev-owner-in-dubai-counts-on-plusx-electric`,
      lastModified    : new Date("2026-04-22T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}how-to-take-care-of-your-ev-during-the-holidays`,
      lastModified    : new Date("2026-04-29T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}why-ev-owners-trust-plusx-electric-when-their-ev-battery-drains-on-dubai-roads`,
      lastModified    : new Date("2026-05-19T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}why-diesel-ev-chargers-are-not-the-eco-friendly-solution-dubai-needs`,
      lastModified    : new Date("2026-05-20T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}why-dubai-ev-owners-are-choosing-roadside-assistance-over-towing`,
      lastModified    : new Date("2026-05-27T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}emergency-ev-charging-in-dubai`,
      lastModified    : new Date("2026-07-10T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}ev-charging-in-dubai-guide`,
      lastModified    : new Date("2026-07-17T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}doorstep-ev-charging-in-dubai`,
      lastModified    : new Date("2026-06-24T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}what-is-portable-ev-charging-and-how-does-it-work-in-dubai`,
      lastModified    : new Date("2026-07-05T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}ev-solutions-in-dubai`,
      lastModified    : new Date("2026-07-14T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}ev-charging-problems-dubai`,
      lastModified    : new Date("2026-07-14T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}ac-vs-dc-ev-chargers`,
      lastModified    : new Date("2026-07-14T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}how-to-find-the-nearest-public-ev-charging-station-in-dubai`,
      lastModified    : new Date("2026-07-19T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}dead-ev-in-a-dubai-basement-parking-garage`,
      lastModified    : new Date("2026-07-19T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}can-someone-bring-a-charge-to-my-ev-in-dubai`,
      lastModified    : new Date("2026-07-21T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}ev-battery-mistakes-dubai`,
      lastModified    : new Date("2026-07-21T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}ev-charger-installation-mistakes-uae`,
      lastModified    : new Date("2026-07-26T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}ev-charging-options-uae`,
      lastModified    : new Date("2026-07-28T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },

    {
      url             : `${baseUrl}about-us`,
      lastModified    : new Date("2026-06-19T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}contact-us`,
      lastModified    : new Date("2026-06-19T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.7,
    },
    {
      url             : `${baseUrl}terms-and-conditions`,
      lastModified    : new Date("2026-06-19T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.3,
    },
    {
      url             : `${baseUrl}privacy-policy`,
      lastModified    : new Date("2026-06-19T05:44:30+01:00"),
      changeFrequency : "weekly",
      priority        : 0.3,
    },
  ];
}