//Chargers Images
import PortableEVChargerAC    from "@/assets/images/EvChargerInstallation/Products/Chargers/PortableEVChargerAC.webp";
import WallChargerAC          from "@/assets/images/EvChargerInstallation/Products/Chargers/WallChargerAC.webp";
import MovableChargerDC       from "@/assets/images/EvChargerInstallation/Products/Chargers/MovableChargerDC.webp";
import WallboxChargerDC       from "@/assets/images/EvChargerInstallation/Products/Chargers/WallboxChargerDC.webp";
import HighPowerDCCharger     from "@/assets/images/EvChargerInstallation/Products/Chargers/HighPowerDCCharger.webp";

//Accessories Images
import FixedBase              from "@/assets/images/EvChargerInstallation/Products/Accessories/FixedBase.webp";
import Bag                    from "@/assets/images/EvChargerInstallation/Products/Accessories/Bag.webp";

// import CCS2CCS1 from "../assets/EvChargerInstallation/Products/Accessories/CCS2-CCS1.webp";
// import CCS2TOGBT from "../assets/EvChargerInstallation/Products/Accessories/CCS2-TO-GBT.webp";
// import NACSTOT2 from "../assets/EvChargerInstallation/Products/Accessories/NACS-TO-T2.webp";
// import TYPE2TYPE1 from "../assets/EvChargerInstallation/Products/Accessories/TYPE2-TYPE1.webp";
// import T2T2 from "../assets/EvChargerInstallation/Products/Accessories/T2-T2.webp";

export const chargers = [
  { 
    id: "evc-001",
    name: "Portable EV Charger AC 7KW",
    slug: "Portable EV Charger AC 7KW".toLowerCase().replace(/\s+/g, "-"),
    price: "700 AED",
    previousPrice: "1000 AED",
    image: PortableEVChargerAC,
    description: "The PlusX Portable EV Charger is a powerful and compact charging solution designed for home, apartment, villa, office, commercial buildings, and fleet operations.",
    compatible: "Works with all EVs",
    output: "AC 7 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX Portable EV Charger – Home & Commercial EV Charging",
    metaDescription: "Buy the PlusX Portable EV Charger – a 7 kW AC smart charger for homes, offices & fleets. Compatible with all GCC EVs. Safe, fast, and easy plug-and-charge.",

    introData: {
      title: "PlusX Portable EV Charger — Smart Charging for Home, Office & Fleets",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Portable EV Charger is a compact, powerful, and easy to use 7 kW AC charger designed for homes, apartments, villas, offices, commercial spaces, and fleet operations. Fully compatible with all GCC electric vehicles, it offers safe and reliable charging with built-in protection against voltage, current, and temperature fluctuations. Its plug and charge design makes daily EV charging simple and convenient without complex installation. Ideal for EV owners and businesses looking for a dependable, portable solution, the PlusX Portable EV Charger delivers unmatched flexibility, universal compatibility, and performance for every charging need in the GCC.`,
    }
    ,
    features: {
      items: [
        "Portable EV Charger cable with ICCB, CE, UKCA, RoHS",
        "Type 2 IEC62196 EV charging cable TPU jacket (CE/TUV certified)",
        "0.96'' LCD screen & Indicator Light to show work situation (R/G/B)",
        "RCD protection: 30mA AC",
        "IP65, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "16A with BS/Schuko power plug, 32A with blue CEE plug",
        "Shell by thermoplastic PC94V-0, abrasion protection with current switch button / delay button",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-002",
    name: "Portable EV Charger AC 11KW",
    slug: "Portable EV Charger AC 11KW".toLowerCase().replace(/\s+/g, "-"),
    price: "800 AED",
    previousPrice: "1000 AED",
    image: PortableEVChargerAC,
    description: "The PlusX Portable EV Charger is a smart, compact, and reliable charging solution built for every kind of space — whether it’s your home, apartment, villa, office, commercial site, or even a full fleet operation.",
    compatible: "Works with all EVs",
    output: "AC 11 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX Portable EV Charger | Fast 11kW 3-Phase EV Charging",
    metaDescription: "Buy the PlusX Portable EV Charger — a compact, safe, and powerful EV charger 11kW 3 phase, compatible with all GCC EVs. Perfect for homes, offices, and fleets.",

    introData: {
      title: "PlusX Portable EV Charger – 11kW 3-Phase EV Charging Solution",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Portable EV Charger is a compact and powerful EV charger 11kW 3 phase, designed for homes, apartments, villas, offices, commercial buildings, and fleet operations. Fully compatible with all GCC electric vehicles, it delivers safe and reliable charging with built-in protection against voltage, current, and temperature fluctuations. Its plug-and-charge design requires no complex installation, offering instant convenience for daily use. Ideal for EV owners and businesses seeking a portable, dependable charging option, the PlusX Portable EV Charger provides exceptional flexibility, universal compatibility, and consistent performance across every charging environment in the GCC.`,
    }
    ,
    features: {
      items: [
        "Portable EV Charger cable with ICCB, CE, UKCA, RoHS",
        "Type 2 IEC62196 EV charging cable TPU jacket (CE/TUV certified)",
        "0.96'' LCD screen & Indicator Light to show work situation (R/G/B)",
        "RCD protection: 30mA AC",
        "IP65, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "16A with BS/Schuko power plug, 32A with blue CEE plug",
        "Shell by thermoplastic PC94V-0, abrasion protection with current switch button / delay button",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-003",
    name: "Wall Charger AC 7KW",
    slug: "Wall Charger AC 7KW".toLowerCase().replace(/\s+/g, "-"),
    price: "999 AED",
    previousPrice: "1499 AED",
    image: WallChargerAC,
    description: "The PlusX Wall Charger AC 7kW – Type 2 offers safe, reliable, and easy home or workplace EV charging. Weather resistance, app-enabled, and fully compatible with all GCC electric vehicles.",
    compatible: "Works with all EVs",
    output: "AC 7 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX 7kW Wall Charger | Type 2 Home & Home EV Charging",
    metaDescription: "The PlusX Wall Charger AC 7kW – Type 2 offers safe, reliable, and easy home or workplace EV charging. Weatherproof, app-enabled, and fully compatible with all GCC electric vehicles.",

    introData: {
      title: "PlusX Wall Charger AC 7kW – Type 2 Home & Office EV Charging Solution",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Wall Charger AC 7kW – Type 2 is a reliable, easy to use EV wall charger designed for seamless charging at home or the workplace. Built with a durable Type 2 cable and clear LED indicator lights, it allows users to track charging status at a glance. Engineered for safety, it includes leakage protection, overcurrent control, surge protection, and temperature safeguards to ensure a stable charging experience.`,
      content2: `This smart charger supports card swipe, plug and play, or app-controlled charging, giving you total flexibility. Its weather resistance design makes it ideal for indoor and outdoor installations. Fully compatible with all GCC electric vehicles, the PlusX Wall Charger is the perfect choice for EV owners looking for a dependable and efficient home or commercial charging solution.`,
    }
    ,
    features: {
      items: [
        "Wall EV Charger, CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation (R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-004",
    name: "Wall Charger AC 11kW",
    slug: "Wall Charger AC 11kW".toLowerCase().replace(/\s+/g, "-"),
    price: "1199 AED",
    previousPrice: "1499 AED",
    image: WallChargerAC,
    description: "The PlusX Wall Charger AC 11kW delivers safe and easy EV charging at home or work. Weather-resistant, app-enabled, and equipped with a durable Type 2 cable and advanced safety features.",
    compatible: "Works with all EVs",
    output: "AC 11 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX 11kW Wall Charger | Type 2 Home & Commercial EV Charging",
    metaDescription: "PlusX 11kW Wall Charger Type 2  weather resistance EV charging for home, villa and offices. App-enabled, plug & play, and built with advanced safety protections.",

    introData: {
      title: "PlusX Wall Charger AC 11kW – Type 2  Home & Commercial EV Charger",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Wall Charger AC 11kW – Type 2 is a reliable and easy to use wall-mounted EV charger designed for  home and commercial charging. Built with a durable Type 2 charging cable and clear indicator lights, it allows you to monitor charging status instantly.`,
      content2: `Engineered with advanced safety protections, including leakage detection, overcurrent control, surge protection, and temperature safeguards—it ensures secure and stable charging every time. The charger supports card swipe, plug and play, and app-controlled charging, giving users complete flexibility. With its weather resistance design and easy installation, the PlusX 11kW Wall Charger is an ideal choice for EV owners seeking a safe, efficient, and long-lasting charging solution.`,
    }
    ,
    features: {
      items: [
        "Wall EV Charger, CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation (R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-005",
    name: "Wall Charger AC 22kW",
    slug: "Wall Charger AC 22kW".toLowerCase().replace(/\s+/g, "-"),
    price: "1699 AED",
    previousPrice: "2000 AED",
    image: WallChargerAC,
    description: "The PlusX Wall Charger AC 22kW offers reliable, safe EV charging for home or work. Weather-resistant, app-enabled, and equipped with a Type 2 cable, advanced protections, and a trusted 3-year warranty.",
    compatible: "Works with all EVs",
    output: "AC 22 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX 22kW Wall Charger | Type 2 Home & Office EV Charging",
    metaDescription: "PlusX 22kW Wall Charger Type 2—safe, weather-resistant EV charging for home, villa, office, and workplace installations. App-enabled with advanced protections and a 3-year warranty.",

    introData: {
      title: "PlusX Wall Charger AC 22kW – Type 2 Commercial and Residential EV Charging Solution",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Wall Charger AC 22kW – Type 2 is a dependable and easy to use wall-mounted EV charger, ideal for home, villa, office, and workplace installations. It features a durable Type 2 charging cable with clear indicator lights for quick charging status visibility.`,
      content2: `Built with essential safety protections—including leakage detection, overcurrent control, surge protection, and temperature safeguards—it ensures safe and stable charging for all GCC electric vehicles. Supporting card swipe, plug and play, and app-controlled charging, it offers flexible usage for both residential and commercial needs. Its weather-resistant design makes it suitable for indoor or outdoor installation, and it comes with a 3-year warranty for long-term reliability.`,
    }
    ,
    features: {
      items: [
        "Wall EV Charger, CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation (R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-006",
    name: "Movable Charger DC 20kW",
    slug: "Movable Charger DC 20kW".toLowerCase().replace(/\s+/g, "-"),
    price: "23000 AED",
    previousPrice: "25000 AED",
    image: MovableChargerDC,
    description: "The PlusX Movable Charger DC 20kW – CCS2 is a portable, high-performance DC charger designed for fast on-site EV charging. Easy to set up and compatible with all GCC vehicles, ideal for apartments, villas, warehouses, hotels, malls, and commercial spaces.",
    compatible: "Works with all EVs",
    output: "DC 20 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX DC 20kW Movable Charger | Portable CCS2 EV Charging",
    metaDescription: "PlusX Movable Charger DC 20kW CCS2—portable, safe, and easy on-site DC charging. Ideal for villas, apartments, hotels, malls & warehouses. Compatible with all GCC EVs.",

    introData: {
      title: "PlusX Movable Charger DC 20kW – CCS2 Portable On-Site DC Fast EV Charging Solution",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Movable Charger DC 20kW – CCS2 is a portable and powerful DC charging solution built for flexible, on-site electric vehicle charging across multiple environments. Designed for mobility and fast deployment, it features a durable CCS2 charging cable, clear indicator lights, and a full suite of safety protections, including leakage detection, overcurrent control, surge protection, and temperature safeguards.`,
      content2: `This smart charger supports card swipe, plug-and-play, and app-controlled charging, giving users complete control and convenience. With an open power cord or plug-in setup option, installation becomes quick and effortless, making it ideal for temporary or permanent charging points. Perfect for open spaces, apartments, villas, warehouses, commercial buildings, hotels, malls, and fleet areas, the PlusX Movable Charger DC 20kW provides fast DC charging exactly where it's needed. Fully compatible with all GCC electric vehicles, it offers unmatched flexibility for property owners, businesses, and EV operators.`,
    }
    ,
    features: {
      items: [
        "CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation(R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-007",
    name: "Movable Charger DC 30kW",
    slug: "Movable Charger DC 30kW".toLowerCase().replace(/\s+/g, "-"),
    price: "28500 AED",
    previousPrice: "30000 AED",
    image: MovableChargerDC,
    description: "The PlusX Movable Charger DC 30kW – CCS2 is a portable, high-performance DC charger designed for fast on-site EV charging. Easy to set up, backed by a 3-year warranty, and compatible with all GCC vehicles—ideal for villas, apartments, warehouses, hotels, malls, and commercial spaces.",
    compatible: "Works with all EVs",
    output: "DC 30 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX DC 30kW Movable Charger | Portable CCS2 EV Charging",
    metaDescription: "PlusX Movable Charger DC 30kW CCS2—portable, safe on-site DC charging with a 3-year warranty. Ideal for villas, apartments, hotels, malls, warehouses & commercial spaces.",

    introData: {
      title: "PlusX Movable Charger DC 30kW – CCS2 Portable On-Site DC EV Charging Solution",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Movable Charger DC 30kW – CCS2 is a portable and powerful DC charging solution designed for flexible, on-site EV charging across a wide range of environments. Built for mobility and quick deployment, it comes with a durable CCS2 charging cable, clear indicator lights, and comprehensive safety protections including leakage detection, overcurrent control, surge protection, and temperature safeguards.`,
      content2: `It supports card swipe, plug-and-play, and app-controlled charging, giving users complete control and convenience. With an open power cord or plug-in setup option, installation is fast and effortless, making it suitable for both temporary and permanent charging points. Perfect for open spaces, apartments, villas, warehouses, commercial buildings, hotels, malls, and fleet areas, the PlusX Movable Charger DC 30kW delivers dependable DC charging wherever it's needed. Fully compatible with all GCC electric vehicles and backed by a 3-year warranty, it offers unmatched flexibility, reliability, and long-term value for businesses and property owners.`,
    }
    ,
    features: {
      items: [
        "CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation(R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-008",
    name: "Wallbox Charger DC 20kW",
    slug: "Wallbox Charger DC 20kW".toLowerCase().replace(/\s+/g, "-"),
    price: "22000 AED",
    previousPrice: "30000 AED",
    image: WallboxChargerDC,
    description: "The PlusX Wallbox Charger DC 20kW – CCS2 delivers reliable, efficient DC charging for homes, villas, apartments, and commercial spaces. Easy to install, safe, and compatible with all GCC EVs—perfect for open spaces, warehouses, hotels, malls, and more.",
    compatible: "Works with all EVs",
    output: "DC 20 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX DC 20kW Wallbox | Home, Villa & Apartment DC Charging",
    metaDescription: "PlusX DC 20kW Wallbox Charger—compact, safe, and easy DC charging for homes, villas, and apartments. CCS2 connector, app control, and full safety protections. GCC EV compatible.",

    introData: {
      title: "PlusX Wallbox Charger DC 20kW – CCS2 Home, Villa & Apartment DC EV Charging Solution",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Wallbox Charger DC 20kW – CCS2 is a compact and efficient DC wall-mounted charger designed for fast, reliable EV charging in any setting. It features a durable CCS2 cable, clear indicator lights, and essential safety protections, including leakage, overcurrent, surge, and temperature safeguards.`,
      content2: `Supporting card swipe, plug & play, and app-controlled charging, it offers flexible operation for all user needs. Easy to install and compatible with all GCC vehicles, it is ideal for DC chargers for home, DC charger for villa, DC charger for apartment, as well as warehouses, commercial buildings, hotels, malls, and open spaces.`,
    }
    ,
    features: {
      items: [
        "CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation(R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-009",
    name: "Wallbox Charger DC 30kW",
    slug: "Wallbox Charger DC 30kW".toLowerCase().replace(/\s+/g, "-"),
    price: "28500 AED",
    previousPrice: "30000 AED",
    image: WallboxChargerDC,
    description: "The PlusX Wallbox Charger DC 30kW – CCS2 delivers dependable DC charging for homes, villas, apartments, and commercial spaces. With flexible card, plug & play, and app control, it provides a safe, easy, and efficient solution compatible with all GCC EVs.",
    compatible: "Works with all EVs",
    output: "DC 30 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX DC 30kW Wallbox | Home, Villa & Apartment DC Charger",
    metaDescription: "PlusX Wallbox DC 30kW CCS2—safe, compact DC charging for homes, villas, apartments, and commercial sites. App control, plug & play, and full safety features. GCC EV compatible.",

    introData: {
      title: "PlusX Wallbox Charger DC 30kW – CCS2 Powerful DC Charging for Homes, Villas & Apartments",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Wallbox Charger DC 30kW – CCS2 is a robust wall-mounted DC charging unit designed to bring high-efficiency EV charging into residential and commercial environments. Built with a strong CCS2 connector and clear status indicators, it ensures smooth operation and easy monitoring.`,
      content2: `This charger includes advanced safety layers—leakage protection, overcurrent management, surge control, and thermal safeguards—offering a secure charging experience for all GCC electric vehicles. Users can choose between card swipe, simple plug-and-charge, or app-based control, making it suitable for a variety of installation needs. Engineered for convenience and quick setup, the PlusX DC 30kW Wallbox is an excellent choice for DC chargers for home, DC charger for villa, DC charger for apartment, as well as warehouses, hotels, malls, and other commercial locations. It’s a reliable, space-efficient solution for properties that need consistent and powerful DC charging without a large infrastructure footprint.`,
    }
    ,
    features: {
      items: [
        "CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation(R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-010",
    name: "High Power DC 60KW",
    slug: "High Power DC 60KW".toLowerCase().replace(/\s+/g, "-"),
    price: "75750 AED",
    previousPrice: "100000 AED",
    image: HighPowerDCCharger,
    description: "The PlusX High Power DC 60kW Charger is a heavy-duty, high-performance fast charger built for public and commercial locations. With CCS2 cables, app control, and full safety protections, it delivers reliable, efficient DC charging for all GCC-compatible EVs.",
    compatible: "Works with all EVs",
    output: "DC 60 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX DC 60kW Fast Charger | High-Power Commercial EV Charging",
    metaDescription: "PlusX High Power DC 60kW fast, durable EV charger for public and commercial sites. With app control, full safety protections and GCC EV compatible.",

    introData: {
      title: "PlusX High Power DC 60kW – Heavy-Duty Fast EV Charger for Public & Commercial Use",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX High Power DC 60kW Fast EV Charger is a durable, high-performance charging station built for public and commercial use. Designed to deliver consistent fast charging, it features strong CCS2 cables, easy-to-read indicator lights, and advanced safety protections such as leakage, overcurrent, surge, and temperature control.`,
      content2: `Supporting card swipe, plug & play, and app-controlled charging, it offers flexible operation for all users. Its weatherproof, heavy-duty build makes it suitable for outdoor and indoor installations. Fully compatible with all GCC electric vehicles, it provides reliable, efficient DC charging for busy commercial locations, fleets, malls, hotels, and more.`,
    }
    ,
    features: {
      items: [
        "CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation(R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "evc-011",
    name: "High Power DC 120KW",
    slug: "High Power DC 120KW".toLowerCase().replace(/\s+/g, "-"),
    price: "86500 AED",
    previousPrice: "100000 AED",
    image: HighPowerDCCharger,
    description: "The PlusX High Power DC 120kW Charger delivers high-speed, high-capacity EV charging for public stations and commercial sites. With CCS2 support, app control, and robust safety features, it ensures dependable, efficient charging for all GCC electric vehicles.",
    compatible: "Works with all EVs",
    output: "DC 120 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX DC 120kW Fast EV Charger | High Power EV Charger for GCC Vehicles",
    metaDescription: "PlusX High Power DC 120kW rapid, reliable EV charging for personal and commercial sites. CCS2, app control, and full safety protections. Built for heavy duty GCC EV use.",

    introData: {
      title: "PlusX 120kW Fast DC Charger – Heavy-Duty Public & Commercial EV Charging",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX High Power DC 120kW Fast EV Charger is engineered for locations that require rapid, high-capacity charging to support heavy EV traffic. Ideal for public charging hubs, commercial complexes, fleet depots, and large venues, it provides powerful DC charging with exceptional reliability.`,
      content2: `Equipped with durable CCS2 connectors and bright indicator lights, it ensures smooth user interaction and clear charging visibility. The charger includes a complete protection system—covering leakage, overcurrent, surge, and temperature control—to maintain safe operation at high loads. With support for card authentication, plug-and-charge, and app-based management, operators gain full flexibility in how charging is delivered. Built with a strong, weather-resistant enclosure, the PlusX DC 120kW charger is designed for long-term outdoor and indoor performance. Fully compatible with all GCC EVs, it is the ideal solution for providers seeking fast, stable, and scalable DC charging infrastructure.`,
    }
    ,
    features: {
      items: [
        "CE (EN61851), UKCA, RoHS, TUV, CB",
        "EV charging cable TPU jacket  (CE EN62196 / TUV certified)",
        "Indicator Light to show work situation(R/G/B)",
        "Leakage protection: Type B (RCD 30mA AC+6mA DC)",
        "IP54, Weather proof; Leakage current protection; Impact resistance, Over current protection, Ground protection, Surge protection, O/U voltage protection, O/U frequency protection, Over temp protection",
        "Power cord open, ready to assemble into electricity / or with power plug",
        "Start mode: card swipe / plug & play / App control",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
];

export const accessories = [
  { 
    id: "eva-001",
    name: "Wall Mount Bracket for Portable EV Charger",
    slug: "Wall Mount Bracket for Portable EV Charger".toLowerCase().replace(/\s+/g, "-"),
    price: "30 AED",
    previousPrice: "50 AED",
    image: FixedBase,
    description: "A strong and durable wall mount bracket designed to securely hold your portable EV charger. Keeps charging setups neat, organized, and protected in homes, villas, offices, and commercial spaces.",
    compatible: "Portable EV Charger 7KW & 11KW",
    output: "AC 7 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX Wall Mount Bracket | Portable EV Charger Holder",
    metaDescription: "PlusX Wall Mount Bracket—secure, durable wall holder for portable EV chargers. Keeps charging setups organized and protected in homes, villas, offices, and commercial spaces.",

    introData: {
      title: "PlusX Wall Mount Bracket – Secure Holder for Portable EV Chargers",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Wall Mount Bracket for Portable EV Charger is a strong and durable mounting solution designed to securely hold your portable EV charger in place. Built for stability and convenience, it keeps your charger neatly positioned during use, prevents cable clutter, and protects the device from accidental drops or damage.`,
      content2: `Perfect for homes, villas, offices, and commercial spaces, this bracket ensures a clean and organized charging setup while making daily EV charging more convenient. Easy to install and built with high-quality materials, it provides a long-lasting, reliable support base for your portable EV charger.`,
    }
    ,
    features: {
      items: [
        "A sturdy and reliable base designed to securely hold your Portable EV Charger, keeping it stable and organized during charging",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },
  {
    id: "eva-002",
    name: "Carry Bag for Portable EV Charger",
    slug: "Carry Bag for Portable EV Charger".toLowerCase().replace(/\s+/g, "-"),
    price: "150 AED",
    previousPrice: "200 AED",
    image: Bag,
    description: "A durable, waterproof carry bag designed to protect and store your portable EV charger. Offers safe, convenient transport with premium materials, secure closure, and an easy-carry handle.",
    compatible: "Portable EV Charger 7KW & 11KW",
    output: "AC 11 KW",
    warrenty: "3 years warranty from the date of installation",
    metaTitle: "PlusX Carry Bag | Waterproof Portable EV Charger Storage",
    metaDescription: "PlusX Carry Bag—waterproof, durable storage for portable EV chargers. Protects against dust, moisture, and damage while ensuring easy, organized transport anywhere you go.",

    introData: {
      title: "PlusX Carry Bag – Waterproof Storage Bag for Portable EV Chargers",
      // buttonText: "Request Assistance",
      // buttonText: "Download the app to required services",
      // isDisplayButton: true,
      // link: '#',
      content: `The PlusX Carry Bag for Portable EV Charger is a premium, waterproof storage and travel solution designed to protect your charger wherever you go. Crafted from durable, high-quality materials, it keeps your portable EV charger safe from dust, moisture, scratches, and everyday wear.`,
      content2: `With its spacious interior, secure zipper closure, and easy-carry handle, this bag ensures hassle-free transport and organized storage—whether at home, in your vehicle, or on the move. Perfect for EV owners who want convenience, protection, and long-lasting durability for their portable EV charging equipment.`,
    }
    ,
    features: {
      items: [
        "Premium storage and transport solution for your portable EV charger, ensuring convenience and protection on the go",
      ],
      buttonText: "Specification",
      buttonLink: "#",
    },
  },

  // {
  //   id: "eva-003",
  //   name: "CCS2 to CCS1 Adapter",
  //   slug: "CCS2 to CCS1 Adapter".toLowerCase().replace(/\s+/g, "-"),
  //   price: "1100 AED",
  //   previousPrice: "1499 AED",
  //   image: CCS2CCS1,
  //   description: "The PlusX Portable EV Charger is a powerful and compact charging solution designed for home, apartment, villa, office, commercial buildings, and fleet operations.",
  //   compatible: "European/GCC spec to American spec",
  //   output: "AC 7 KW",
  //   warrenty: "2 years warranty from the date of installation",

  //   introData: {
  //     title: "PlusX Portable EV Charger — Smart Charging for Home, Office & Fleets",
  //     // buttonText: "Request Assistance",
  //     // buttonText: "Download the app to required services",
  //     // isDisplayButton: true,
  //     // link: '#',
  //     content: `The PlusX Portable EV Charger is a compact, powerful, and easy-to-use 7 kW AC charger designed for homes, apartments, villas, offices, commercial spaces, and fleet operations. Fully compatible with all GCC electric vehicles, it offers safe, and reliable charging with built-in protection against voltage, current, and temperature fluctuations. Its plug-and-charge design makes daily EV charging simple and convenient without complex installation. Ideal for EV owners and businesses looking for a dependable, portable solution, the PlusX Portable EV Charger delivers unmatched flexibility, universal compatibility, and performance for every charging need in the GCC.`,
  //   }
  //   ,
  //   features: {
  //     items: [
  //       "Enables high-speed DC charging for CCS1 vehicles via CCS2 charging stations (supports up to 200A / 1000V depending on charger capacity)",
  //       "Works with most CCS1-standard electric vehicles including models from Ford, Chevrolet, Kia, Hyundai (US spec), and others",
  //       "Built-in overvoltage, overcurrent, and short-circuit protection ensuring safe and stable charging",
  //       "High-grade flame-retardant materials and weather-resistant casing (IP54 or higher) for outdoor use",
  //       "No setup or configuration required — simply connect the adapter to the CCS2 charger and plug into your CCS1 vehicle",
  //       "Ideal for EV owners traveling between regions where CCS2 infrastructure is more common (e.g., Europe, Middle East, Asia)",
  //       "Lightweight design for easy storage in your vehicle’s trunk or glove compartment",
  //     ],
  //     buttonText: "Specification",
  //     buttonLink: "#",
  //   },
  // },
  // {
  //   id: "eva-004",
  //   name: "CCS2 TO GBT",
  //   slug: "CCS2 TO GBT".toLowerCase().replace(/\s+/g, "-"),
  //   price: "3500 AED",
  //   previousPrice: "4000 AED",
  //   image: CCS2TOGBT,
  //   description: "The PlusX Portable EV Charger is a powerful and compact charging solution designed for home, apartment, villa, office, commercial buildings, and fleet operations.",
  //   compatible: "European/GCC spec to Chinese spec",
  //   output: "AC 11 KW",
  //   warrenty: "2 years warranty from the date of installation",

  //   introData: {
  //     title: "PlusX Portable EV Charger — Smart Charging for Home, Office & Fleets",
  //     // buttonText: "Request Assistance",
  //     // buttonText: "Download the app to required services",
  //     // isDisplayButton: true,
  //     // link: '#',
  //     content: `The PlusX Portable EV Charger is a compact, powerful, and easy-to-use 7 kW AC charger designed for homes, apartments, villas, offices, commercial spaces, and fleet operations. Fully compatible with all GCC electric vehicles, it offers safe, and reliable charging with built-in protection against voltage, current, and temperature fluctuations. Its plug-and-charge design makes daily EV charging simple and convenient without complex installation. Ideal for EV owners and businesses looking for a dependable, portable solution, the PlusX Portable EV Charger delivers unmatched flexibility, universal compatibility, and performance for every charging need in the GCC.`,
  //   }
  //   ,
  //   features: {
  //     items: [
  //       "Supports high-power DC charging (up to 1000V / 250A, depending on charger and vehicle capacity) for efficient charging performance",
  //       "Allows GB/T vehicles to use the more widely available CCS2 charging infrastructure in regions such as the UAE, Europe, and the Middle East",
  //       "Built-in safeguards against overvoltage, overcurrent, overheat, and short circuits",
  //       "IP54/IP55-rated construction for outdoor charging use; made with flame-retardant, high-impact materials for durability",
  //       "No software or setup required - just connect the adapter between the CCS2 charger and your GB/T vehicle",
  //       "Lightweight and easy to carry, perfect for long-distance drivers and fleet operators",
  //     ],
  //     buttonText: "Specification",
  //     buttonLink: "#",
  //   },
  // },
  // {
  //   id: "eva-005",
  //   name: "CCS2 to NACS (Tesla) Adapter",
  //   slug: "CCS2 to NACS (Tesla) Adapter".toLowerCase().replace(/\s+/g, "-"),
  //   price: "950 AED",
  //   previousPrice: "1000 AED",
  //   image: NACSTOT2,
  //   description: "The PlusX Portable EV Charger is a powerful and compact charging solution designed for home, apartment, villa, office, commercial buildings, and fleet operations.",
  //   compatible: "Tesla Model 3/Y/S/X - GCC Spec to Tesla",
  //   output: "AC 22 KW",
  //   warrenty: "2 years warranty from the date of installation",

  //   introData: {
  //     title: "PlusX Portable EV Charger — Smart Charging for Home, Office & Fleets",
  //     // buttonText: "Request Assistance",
  //     // buttonText: "Download the app to required services",
  //     // isDisplayButton: true,
  //     // link: '#',
  //     content: `The PlusX Portable EV Charger is a compact, powerful, and easy-to-use 7 kW AC charger designed for homes, apartments, villas, offices, commercial spaces, and fleet operations. Fully compatible with all GCC electric vehicles, it offers safe, and reliable charging with built-in protection against voltage, current, and temperature fluctuations. Its plug-and-charge design makes daily EV charging simple and convenient without complex installation. Ideal for EV owners and businesses looking for a dependable, portable solution, the PlusX Portable EV Charger delivers unmatched flexibility, universal compatibility, and performance for every charging need in the GCC.`,
  //   }
  //   ,
  //   features: {
  //     items: [
  //       "Provides high-power DC charging (up to 1000V / 250A, depending on charger and vehicle compatibility) for rapid charging at public CCS2 stations",
  //       "Designed for Tesla vehicles equipped with NACS connectors, enabling use of CCS2 chargers commonly found across the UAE, Europe, and Asia",
  //       "Equipped with overcurrent, overvoltage, overtemperature, and leakage protection systems to ensure safe and stable charging sessions",
  //       "Durable, flame-retardant housing with IP54/IP55 protection rating for outdoor charging use",
  //       "No configuration or updates needed - simply connect to the CCS2 charger and your Tesla vehicle",
  //       "Lightweight and easy to store; ideal for road trips or areas with mixed charging infrastructure",
  //     ],
  //     buttonText: "Specification",
  //     buttonLink: "#",
  //   },
  // },
  // {
  //   id: "eva-006",
  //   name: "Type 2 to Type 1 Adapter",
  //   slug: "Type 2 to Type 1 Adapter".toLowerCase().replace(/\s+/g, "-"),
  //   price: "469 AED",
  //   previousPrice: "500 AED",
  //   image: TYPE2TYPE1,
  //   description: "The PlusX Portable EV Charger is a powerful and compact charging solution designed for home, apartment, villa, office, commercial buildings, and fleet operations.",
  //   compatible: "American Specs to GCC/European Specs",
  //   output: "DC 20 KW",
  //   warrenty: "2 years warranty from the date of installation",

  //   introData: {
  //     title: "PlusX Portable EV Charger — Smart Charging for Home, Office & Fleets",
  //     // buttonText: "Request Assistance",
  //     // buttonText: "Download the app to required services",
  //     // isDisplayButton: true,
  //     // link: '#',
  //     content: `The PlusX Portable EV Charger is a compact, powerful, and easy-to-use 7 kW AC charger designed for homes, apartments, villas, offices, commercial spaces, and fleet operations. Fully compatible with all GCC electric vehicles, it offers safe, and reliable charging with built-in protection against voltage, current, and temperature fluctuations. Its plug-and-charge design makes daily EV charging simple and convenient without complex installation. Ideal for EV owners and businesses looking for a dependable, portable solution, the PlusX Portable EV Charger delivers unmatched flexibility, universal compatibility, and performance for every charging need in the GCC.`,
  //   }
  //   ,
  //   features: {
  //     items: [
  //       "Supports single-phase AC charging up to 7.4kW (230V, 32A), ideal for public and home charging points",
  //       "Enables EVs with Type 1 inlets to connect to Type 2 sockets commonly found across the UAE, Europe, and Asia",
  //       "Equipped with protection features for overcurrent, overvoltage, and overheating to ensure safe charging",
  //       "Built from flame-retardant, high-strength materials with IP54/IP55 protection for outdoor use",
  //       "No configuration or installation required - simply plug the adapter between the charger and the vehicle",
  //       "Portable design makes it easy to carry and store in your EV for daily use or travel",
  //     ],
  //     buttonText: "Specification",
  //     buttonLink: "#",
  //   },
  // },
  // {
  //   id: "eva-007",
  //   name: "Type 2 to Type 2 (GB/T) Adapter",
  //   slug: "Type 2 to Type 2 (GB/T) Adapter".toLowerCase().replace(/\s+/g, "-"),
  //   price: "600 AED",
  //   previousPrice: "1000 AED",
  //   image: T2T2,
  //   description: "The PlusX Portable EV Charger is a powerful and compact charging solution designed for home, apartment, villa, office, commercial buildings, and fleet operations.",
  //   compatible: "Chinese Spec to GCC/European Spec",
  //   output: "DC 30 KW",
  //   warrenty: "2 years warranty from the date of installation",

  //   introData: {
  //     title: "PlusX Portable EV Charger — Smart Charging for Home, Office & Fleets",
  //     // buttonText: "Request Assistance",
  //     // buttonText: "Download the app to required services",
  //     // isDisplayButton: true,
  //     // link: '#',
  //     content: `The PlusX Portable EV Charger is a compact, powerful, and easy-to-use 7 kW AC charger designed for homes, apartments, villas, offices, commercial spaces, and fleet operations. Fully compatible with all GCC electric vehicles, it offers safe, and reliable charging with built-in protection against voltage, current, and temperature fluctuations. Its plug-and-charge design makes daily EV charging simple and convenient without complex installation. Ideal for EV owners and businesses looking for a dependable, portable solution, the PlusX Portable EV Charger delivers unmatched flexibility, universal compatibility, and performance for every charging need in the GCC.`,
  //   }
  //   ,
  //   features: {
  //     items: [
  //       "Enables single-phase or three-phase AC charging (up to 7.4kW / 22kW depending on model and charger capacity)",
  //       "Connects GB/T vehicles to widely available Type 2 chargers across the UAE, Europe, and other global regions",
  //       "Built-in protection against overvoltage, overcurrent, overheating, and leakage for maximum safety",
  //       "Durable construction using flame-retardant, impact-resistant materials with IP54/IP55 protection rating for outdoor use",
  //       "No setup or software required - simply connect the adapter to the Type 2 charger and your GB/T vehicle",
  //       "Compact design makes it easy to store in your vehicle for everyday or travel use",
  //     ],
  //     buttonText: "Specification",
  //     buttonLink: "#",
  //   },
  // },
];
